import type { GrapheCorporatif } from './domaine.js';

/**
 * Graphe de démonstration — entreprises, personnes et avis entièrement fictifs.
 *
 * Le montage est construit pour exercer chaque règle de détection au moins une
 * fois, tout en restant plausible : une société d'exploitation détenue via une
 * société de gestion, un cycle de détention avec une coquille radiée, une
 * reconstitution après dissolution, et une grappe de sociétés partageant une
 * adresse et un administrateur unique.
 *
 * Sert de fixture aux tests et de jeu de démonstration à l'API.
 */
export function grapheDemonstration(): GrapheCorporatif {
  return {
    provenance: {
      source: 'demonstration',
      dateExtraction: '2026-08-12',
      cadence: 'Jeu figé — aucune synchronisation',
      licence: 'Données fictives, libres d’usage',
    },

    entites: [
      {
        id: 'E1',
        neq: '1171234567',
        nomLegal: '9284-1057 Québec Inc.',
        nomsAnterieurs: ['9284-1057 Canada Inc.'],
        formeJuridique: 'societe_par_actions',
        statut: 'immatriculee',
        codeNaics: '484110',
        dateConstitution: '2019-03-14',
      },
      {
        id: 'E2',
        neq: '1163098221',
        nomLegal: 'Gestion Lavallée-Bouchard Inc.',
        nomsAnterieurs: [],
        formeJuridique: 'societe_par_actions',
        statut: 'immatriculee',
        codeNaics: '551112',
        dateConstitution: '2016-09-08',
      },
      {
        id: 'E3',
        neq: '1179834502',
        nomLegal: '9412-8837 Québec Inc.',
        nomsAnterieurs: [],
        formeJuridique: 'societe_par_actions',
        statut: 'radiee_office',
        codeNaics: '531120',
        dateConstitution: '2020-05-21',
        dateDissolution: '2023-11-19',
      },
      {
        id: 'E4',
        neq: '1168459023',
        nomLegal: 'Immobilière du Nordet Ltée',
        nomsAnterieurs: [],
        formeJuridique: 'societe_par_actions',
        statut: 'immatriculee',
        codeNaics: '531120',
        dateConstitution: '2018-02-27',
      },
      {
        id: 'E5',
        neq: '1184002914',
        nomLegal: 'Gestion 9412 Inc.',
        nomsAnterieurs: [],
        formeJuridique: 'societe_par_actions',
        statut: 'immatriculee',
        codeNaics: '531120',
        dateConstitution: '2024-02-08',
      },
      {
        id: 'E6',
        neq: '1190112233',
        nomLegal: 'Services Beauport 2021 Inc.',
        nomsAnterieurs: [],
        formeJuridique: 'societe_par_actions',
        statut: 'radiee_office',
        codeNaics: '561720',
        dateConstitution: '2021-01-15',
        dateDissolution: '2024-06-30',
      },
      {
        id: 'E7',
        neq: '1190445566',
        nomLegal: 'Distribution Vallonet Inc.',
        nomsAnterieurs: [],
        formeJuridique: 'societe_par_actions',
        statut: 'dissoute',
        codeNaics: '414410',
        dateConstitution: '2021-03-02',
        dateDissolution: '2024-09-12',
      },
      {
        id: 'E8',
        neq: '1190778899',
        nomLegal: 'Rénovations Katevale Inc.',
        nomsAnterieurs: [],
        formeJuridique: 'societe_par_actions',
        statut: 'dissoute',
        codeNaics: '236220',
        dateConstitution: '2021-07-19',
        dateDissolution: '2025-01-23',
      },
      {
        id: 'E9',
        neq: '1191002244',
        nomLegal: 'Transport Mégantic-Sud Inc.',
        nomsAnterieurs: [],
        formeJuridique: 'societe_par_actions',
        statut: 'immatriculee',
        codeNaics: '484121',
        dateConstitution: '2022-04-11',
      },
    ],

    personnes: [
      { id: 'P1', nomComplet: 'Chantal Rousseau', variantesNom: [], scoreConfianceIdentite: 1 },
      {
        id: 'P2',
        nomComplet: 'Marc-André Fortin',
        variantesNom: ['Marc A. Fortin'],
        scoreConfianceIdentite: 0.94,
      },
      { id: 'P3', nomComplet: 'Nathalie Girard', variantesNom: [], scoreConfianceIdentite: 1 },
      { id: 'P4', nomComplet: 'Denis Bouchard', variantesNom: [], scoreConfianceIdentite: 1 },
      {
        id: 'P5',
        nomComplet: 'Sylvain Cloutier',
        variantesNom: ['S. Cloutier'],
        scoreConfianceIdentite: 0.88,
      },
    ],

    adresses: [
      {
        id: 'A1',
        adresseNormalisee: '1500 boul René-Lévesque O bureau 2400, Montréal (Québec)',
        codePostal: 'H3B 4W8',
      },
      {
        id: 'A2',
        adresseNormalisee: '425 rue Saint-Jean, Québec (Québec)',
        codePostal: 'G1R 1P5',
      },
      {
        id: 'A3',
        adresseNormalisee: '900 place Victoria, Montréal (Québec)',
        codePostal: 'H4Z 1C3',
        domiciliataireConnu: true,
      },
    ],

    detentions: [
      {
        id: 'D1',
        sourceEntiteId: 'E2',
        cibleEntiteId: 'E1',
        pourcentage: 0.65,
        typeTitre: 'actions ordinaires',
        depuis: '2023-10-03',
        avisReqId: 'REQ-23-402118',
      },
      {
        id: 'D2',
        sourcePersonneId: 'P1',
        cibleEntiteId: 'E1',
        pourcentage: 0.35,
        typeTitre: 'actions ordinaires',
        depuis: '2019-03-14',
        avisReqId: 'REQ-19-088231',
      },
      {
        id: 'D3',
        sourcePersonneId: 'P4',
        cibleEntiteId: 'E2',
        pourcentage: 0.6,
        typeTitre: 'actions votantes',
        depuis: '2016-09-08',
        avisReqId: 'REQ-16-220145',
      },
      {
        id: 'D4',
        sourceEntiteId: 'E3',
        cibleEntiteId: 'E2',
        pourcentage: 0.4,
        typeTitre: 'actions votantes',
        depuis: '2020-06-30',
        avisReqId: 'REQ-20-133907',
      },
      {
        id: 'D5',
        sourceEntiteId: 'E1',
        cibleEntiteId: 'E3',
        pourcentage: 0.51,
        typeTitre: 'actions ordinaires',
        depuis: '2021-08-11',
        avisReqId: 'REQ-21-260554',
      },
      {
        id: 'D6',
        sourceEntiteId: 'E1',
        cibleEntiteId: 'E4',
        pourcentage: 1,
        typeTitre: 'actions ordinaires',
        depuis: '2019-11-05',
        avisReqId: 'REQ-19-311208',
      },
    ],

    administrations: [
      {
        id: 'AD1',
        personneId: 'P2',
        entiteId: 'E1',
        titre: 'Président',
        depuis: '2025-11-28',
        avisReqId: 'REQ-25-390014',
      },
      {
        id: 'AD2',
        personneId: 'P3',
        entiteId: 'E1',
        titre: 'Secrétaire',
        depuis: '2019-03-14',
        avisReqId: 'REQ-19-088231',
      },
      {
        id: 'AD3',
        personneId: 'P2',
        entiteId: 'E3',
        titre: 'Administrateur',
        depuis: '2020-05-21',
        jusquA: '2023-11-19',
        avisReqId: 'REQ-20-119880',
      },
      {
        id: 'AD4',
        personneId: 'P3',
        entiteId: 'E3',
        titre: 'Administratrice',
        depuis: '2020-05-21',
        jusquA: '2023-11-19',
        avisReqId: 'REQ-20-119880',
      },
      {
        id: 'AD5',
        personneId: 'P2',
        entiteId: 'E5',
        titre: 'Administrateur',
        depuis: '2024-02-08',
        avisReqId: 'REQ-24-011276',
      },
      {
        id: 'AD6',
        personneId: 'P3',
        entiteId: 'E5',
        titre: 'Administratrice',
        depuis: '2024-02-08',
        avisReqId: 'REQ-24-011276',
      },
      {
        id: 'AD7',
        personneId: 'P4',
        entiteId: 'E2',
        titre: 'Président',
        depuis: '2016-09-08',
        avisReqId: 'REQ-16-220145',
      },
      {
        id: 'AD8',
        personneId: 'P5',
        entiteId: 'E6',
        titre: 'Administrateur',
        depuis: '2021-01-15',
        jusquA: '2021-11-30',
        avisReqId: 'REQ-21-004411',
      },
      {
        id: 'AD9',
        personneId: 'P5',
        entiteId: 'E7',
        titre: 'Administrateur',
        depuis: '2021-03-02',
        jusquA: '2022-02-14',
        avisReqId: 'REQ-21-030922',
      },
      {
        id: 'AD10',
        personneId: 'P5',
        entiteId: 'E8',
        titre: 'Administrateur',
        depuis: '2021-07-19',
        jusquA: '2022-06-01',
        avisReqId: 'REQ-21-188402',
      },
      {
        id: 'AD11',
        personneId: 'P5',
        entiteId: 'E9',
        titre: 'Administrateur',
        depuis: '2022-04-11',
        jusquA: '2023-03-20',
        avisReqId: 'REQ-22-093311',
      },
    ],

    successions: [],

    liensAdresse: [
      { id: 'L1', adresseId: 'A1', entiteId: 'E1', typeLien: 'siege_social', depuis: '2022-05-01' },
      { id: 'L2', adresseId: 'A2', entiteId: 'E1', typeLien: 'siege_social', depuis: '2019-03-14', jusquA: '2022-05-01' },
      { id: 'L3', adresseId: 'A1', entiteId: 'E2', typeLien: 'siege_social', depuis: '2016-09-08' },
      { id: 'L4', adresseId: 'A2', entiteId: 'E3', typeLien: 'siege_social', depuis: '2020-05-21' },
      { id: 'L5', adresseId: 'A2', entiteId: 'E5', typeLien: 'siege_social', depuis: '2024-02-08' },
      { id: 'L6', adresseId: 'A3', entiteId: 'E4', typeLien: 'siege_social', depuis: '2018-02-27' },
      { id: 'L7', adresseId: 'A1', entiteId: 'E6', typeLien: 'siege_social', depuis: '2021-01-15' },
      { id: 'L8', adresseId: 'A1', entiteId: 'E7', typeLien: 'siege_social', depuis: '2021-03-02' },
      { id: 'L9', adresseId: 'A1', entiteId: 'E8', typeLien: 'siege_social', depuis: '2021-07-19' },
      { id: 'L10', adresseId: 'A1', entiteId: 'E9', typeLien: 'siege_social', depuis: '2022-04-11' },
    ],

    evenements: [
      { id: 'EV1', entiteId: 'E1', type: 'constitution', dateEffective: '2019-03-14', description: 'Constitution sous la dénomination 9284-1057 Canada Inc.', avisReqId: 'REQ-19-088231' },
      { id: 'EV2', entiteId: 'E1', type: 'changement_nom', dateEffective: '2021-06-02', description: 'Changement de dénomination pour 9284-1057 Québec Inc.', avisReqId: 'REQ-21-119042' },
      { id: 'EV3', entiteId: 'E1', type: 'changement_siege', dateEffective: '2022-05-01', description: 'Transfert du siège social de Québec vers Montréal', avisReqId: 'REQ-22-207713' },
      { id: 'EV4', entiteId: 'E1', type: 'transfert_actions', dateEffective: '2023-10-03', description: 'Transfert de 65 % des actions ordinaires à Gestion Lavallée-Bouchard Inc.', avisReqId: 'REQ-23-402118' },
      { id: 'EV5', entiteId: 'E3', type: 'dissolution', dateEffective: '2023-11-19', description: 'Radiation d’office pour défaut de déclaration de mise à jour annuelle', avisReqId: 'REQ-23-448830' },
      { id: 'EV6', entiteId: 'E5', type: 'constitution', dateEffective: '2024-02-08', description: 'Constitution de Gestion 9412 Inc.', avisReqId: 'REQ-24-011276' },
      { id: 'EV7', entiteId: 'E1', type: 'changement_administrateur', dateEffective: '2025-11-28', description: 'Nomination de Marc-André Fortin à la présidence', avisReqId: 'REQ-25-390014' },
      { id: 'EV8', entiteId: 'E2', type: 'constitution', dateEffective: '2016-09-08', description: 'Constitution de Gestion Lavallée-Bouchard Inc.', avisReqId: 'REQ-16-220145' },
      { id: 'EV9', entiteId: 'E3', type: 'constitution', dateEffective: '2020-05-21', description: 'Constitution de 9412-8837 Québec Inc.', avisReqId: 'REQ-20-119880' },
      { id: 'EV10', entiteId: 'E4', type: 'constitution', dateEffective: '2018-02-27', description: 'Constitution d’Immobilière du Nordet Ltée', avisReqId: 'REQ-18-044120' },
      { id: 'EV11', entiteId: 'E6', type: 'dissolution', dateEffective: '2024-06-30', description: 'Radiation d’office', avisReqId: 'REQ-24-266001' },
      { id: 'EV12', entiteId: 'E7', type: 'dissolution', dateEffective: '2024-09-12', description: 'Dissolution volontaire', avisReqId: 'REQ-24-331890' },
      { id: 'EV13', entiteId: 'E8', type: 'dissolution', dateEffective: '2025-01-23', description: 'Dissolution volontaire', avisReqId: 'REQ-25-018844' },
    ],
  };
}
